---
# Copy config files to jenkins home
- name: copy config XML's to jenkins home
  sudo: yes
  copy: src={{ item }} dest={{ jenkins_home }} owner=jenkins mode=600
  with_fileglob:
        - "{{ local_files_dir }}/jenkins/config/*.xml"
  register: configs_copied

- include: plugin-configs/git.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and git.enable_configure

- include: plugin-configs/rally.yml
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ] and rally.enable_configure
