---
# remove security from jenkins
# set useSecurity to false
- name: Disable Jenkins Security
  sudo: yes
  shell: "groovy {{ remote_tmp_folder }}/script/update-node.groovy -n useSecurity -v false {{ jenkins_home }}/config.xml"
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
  register: disable_security

- debug: var=disable_security.stdout_lines

# Restart jenkins service if security was turned off 
# or a new version of jenkins was installed
# to get the latest jenkins-cli.jar
- name: Restarting jenkins service
  sudo: yes
  shell: "service jenkins restart"
  when: "disable_security.stdout.find('Value Before => [useSecurity[attributes={}; value=[true]]]') != -1 or jenkins_install.changed"
  register: restart_jenkins_service

# Wait for jenkins to start
- name: "{{ startup_delay_s | default(45) }}s delay while starting Jenkins"
  wait_for: port=8080 delay={{ startup_delay_s | default(45) }}
  when: restart_jenkins_service.changed
